### ISSUE TITLE
flesh out subsection on Graphical tools

### ISSUE THREAD

**Issue by beanumber** [beanumber/wire21#31]
Currently, this subsection includes `teamcolors` and `sportyR`, which are both packages that make sports data graphics easier to create and better, but in different ways. Are there any other examples of related packages that we could include to help flesh out this section?

**Comment by qntkhvn** [comment]
Another candidate would be [`nflplotR`](https://nflplotr.nflverse.com/articles/nflplotR.html). Graphs like scatterplot with team logos or team logos vs a metric are pretty popular (at least among NFL analytics twitter).

**Comment by beanumber** [comment]
Depending on how we feel about this section at this point, we could also consider adding a defensive shift plot combining sportyR and baseballr.

**Comment by beanumber** [comment]
I think we're good here.
