### ISSUE TITLE
consider a table of CTV

### ISSUE THREAD

**Issue by beanumber** [beanumber/wire21#37]
Reviewer 1:
> As mentioned earlier, Section 5 seems sparse on details, and furthermore it seems odd to choose chess as the case study when it has barely been mentioned previously in the article. I think this section could use a table of some sort, perhaps something that summarizes the CRAN task view at a high level. Another potential would be a figure which shows a typical workflow of sports analytics as explained in the text.

Hmm...could we condense the CRAN Task View into a table? Maybe with one row per sport, and the number of packages, followed by the list of package names as columns?

**Comment by qntkhvn** [comment]
I added the table.
