### ISSUE TITLE
is player tracking data a theme? 

### ISSUE THREAD

**Issue by beanumber** [beanumber/wire21#39]
R1:
> All in all, I think the article explains the ideas well and covers a lot of ground, but more care should be taken towards the organization and what to include as figures. The last half of the paper has a very different pace than the first half. I think a common theme in the paper is the rise in tracking data and how that has impacted sports–perhaps that idea could be better unified and stated in a specific section of the article, or at the very least noted in the conclusion.

We obviously talk about player tracking data, but I wouldn't call it a theme of our paper. Is that a big idea? I don't really think so. How should we respond to this?

**Comment by qntkhvn** [comment]
I would also not call tracking data a theme. I think we should say something like...

It's more of a powerful tool for researchers to dive deeper into the big ideas that already existed (expected points, win prob) and extend previous work. Before tracking data, it was only possible to estimate **between-play** valuation with play-by-play data. With tracking data, it's possible to look at how valuation evolves **within plays**. 

(This is the goal of Ron's going deep paper (which we already mentioned): extending their previous EP and WP work with nflscapr event data to another layer with tracking data.)
