### ISSUE TITLE
EPV for hockey?

### ISSUE THREAD

**Issue by beanumber** [beanumber/wire21#45]
> Page 8, Macdonald (2012?) used expected possession value for ice hockey to evaluate players.

They want us to add a citation to this effect? This is the closest paper I could find:

http://www.hockeyanalytics.com/Research_files/NHL-Expected-Goals-Brian-Macdonald.pdf

But I think this is a different concept, because Brian's paper is about expected goals, but the concept we're discussing is a model for expected goals per possession based on playing tracking data, which didn't exist at the time of publication.

**Comment by qntkhvn** [comment]
What I see on page 8 is "Kumagai & Stokes (2021) offer an EPV metric for ice hockey."  Perhaps they wanted us to add more to (or remove) this, since having one sentence seems a bit odd here? 

(Not sure why they mention Brian)

**Comment by beanumber** [comment]
I think they think that one of Brian's papers include an EPV metric, but I don't see how that would have been possible in 2012. I think the reviewer is confusing "expected goals" with "expected possession value".
